name: AI Code Reviewer

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  review:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install requests openai

    - name: Run AI Code Reviewer
      run: python3 scripts/ai_code_reviewer.py  # Adjust path if needed
      env:
        AI_Code_Reviewer: ${{ secrets.AI_Code_Reviewer }}  # Updated secret name for GitHub token
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}  # OpenAI API Key
